import pytest

class TestHttpClientIntegration:
    @pytest.mark.asyncio
    async def test_real_http_request_with_httpbin(self) -> None: ...
    @pytest.mark.asyncio
    async def test_client_with_plugins_integration(self) -> None: ...
    @pytest.mark.asyncio
    async def test_post_request_with_json_data(self) -> None: ...
    @pytest.mark.asyncio
    async def test_client_context_manager(self) -> None: ...
