import pytest

EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestFunctionalExamples:
    def test_complete_api_workflow(self) -> None: ...
    def test_client_configuration_examples(self) -> None: ...
    def test_query_building_examples(self) -> None: ...
    def test_response_building_examples(self) -> None: ...
    @pytest.mark.asyncio
    async def test_async_client_usage(self) -> None: ...
    def test_error_handling_examples(self) -> None: ...
    def test_builder_pattern_examples(self) -> None: ...
    def test_plugin_integration_examples(self) -> None: ...
    def test_performance_optimization_examples(self) -> None: ...
    def test_security_examples(self) -> None: ...
