class TestFlextApiError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_endpoint(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiValidationError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_field_and_value(self) -> None: ...
    def test_creation_with_endpoint(self) -> None: ...
    def test_long_value_truncation(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiAuthenticationError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_auth_method(self) -> None: ...
    def test_creation_with_endpoint(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiConfigurationError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_config_key(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiConnectionError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_host_and_port(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiProcessingError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_operation(self) -> None: ...
    def test_creation_with_endpoint(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiTimeoutError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_endpoint_and_timeout(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiRequestError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_method_and_endpoint(self) -> None: ...
    def test_creation_with_status_code(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiResponseError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_status_code(self) -> None: ...
    def test_creation_with_response_body(self) -> None: ...
    def test_long_response_body_truncation(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiStorageError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_storage_type(self) -> None: ...
    def test_creation_with_operation(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestFlextApiBuilderError:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_builder_step(self) -> None: ...
    def test_creation_with_additional_context(self) -> None: ...
    def test_default_message(self) -> None: ...

class TestExceptionInheritance:
    def test_flext_api_error_hierarchy(self) -> None: ...
    def test_all_specific_errors_inherit_from_correct_base(self) -> None: ...
    def test_api_specific_errors_inherit_from_api_error(self) -> None: ...

class TestExceptionModuleExports:
    def test_all_exceptions_in_module_all(self) -> None: ...
    def test_all_exports_importable(self) -> None: ...
