import pytest

class TestFlextApi:
    def test_create_api_instance(self) -> None: ...
    def test_factory_function(self) -> None: ...
    def test_health_check(self) -> None: ...
    def test_get_builder(self) -> None: ...
    def test_get_client_initially_none(self) -> None: ...
    def test_create_client(self) -> None: ...
    def test_create_client_with_none_config(self) -> None: ...
    def test_create_client_with_empty_config(self) -> None: ...
    @pytest.mark.asyncio
    async def test_start_service(self) -> None: ...
    @pytest.mark.asyncio
    async def test_stop_service(self) -> None: ...
    @pytest.mark.asyncio
    async def test_service_lifecycle(self) -> None: ...
