import pytest

HTTP_OK: int
EXPECTED_BULK_SIZE: int
EXPECTED_DATA_COUNT: int

class TestFlextApiClientConfig:
    def test_config_creation(self) -> None: ...
    def test_config_with_values(self) -> None: ...
    def test_config_invalid_url(self) -> None: ...

class TestFlextApiClientRequest:
    def test_request_creation(self) -> None: ...
    def test_request_with_string_method(self) -> None: ...
    def test_request_validation_empty_url(self) -> None: ...

class TestFlextApiClientResponse:
    def test_response_creation(self) -> None: ...
    def test_response_with_data(self) -> None: ...
    def test_response_json_method(self) -> None: ...
    def test_response_text_method(self) -> None: ...

class TestFlextApiPlugin:
    def test_plugin_creation(self) -> None: ...
    def test_plugin_with_name(self) -> None: ...
    @pytest.mark.asyncio
    async def test_plugin_before_request(self) -> None: ...
    @pytest.mark.asyncio
    async def test_plugin_after_request(self) -> None: ...
    @pytest.mark.asyncio
    async def test_plugin_on_error(self) -> None: ...

class TestFlextApiClient:
    def test_client_creation(self) -> None: ...
    def test_client_with_config(self) -> None: ...
    def test_client_with_plugins(self) -> None: ...
    def test_health_check(self) -> None: ...
    @pytest.mark.asyncio
    async def test_start_service(self) -> None: ...
    @pytest.mark.asyncio
    async def test_stop_service(self) -> None: ...
    @pytest.mark.asyncio
    async def test_close_method(self) -> None: ...
    @pytest.mark.asyncio
    async def test_context_manager(self) -> None: ...
    def test_create_client(self) -> None: ...
    def test_create_client_with_config(self) -> None: ...
