import pytest

@pytest.mark.asyncio
async def test_health_check_async_returns_coroutine_and_ok() -> None: ...
def test_sync_health_check_runs_ok() -> None: ...
def test_client_creation_and_info_and_legacy() -> None: ...
def test_create_client_impl_valid_and_invalid() -> None: ...
def test_builders_accessors() -> None: ...
