class TestFlextAPIStorage:
    def test_storage_creation(self) -> None: ...
    def test_get_nonexistent_key(self) -> None: ...
    def test_set_and_get(self) -> None: ...
    def test_delete_existing_key(self) -> None: ...
    def test_delete_nonexistent_key(self) -> None: ...
    def test_overwrite_key(self) -> None: ...
