from flext_api import FlextApiError

def test_validation_error_truncates_value_and_http_response() -> None: ...
def test_authentication_error_message_prefix() -> None: ...
def test_timeout_error_context_and_http() -> None: ...
def test_request_response_and_storage_errors() -> None: ...
def test_authorization_notfound_rate_limit_errors() -> None: ...
def test_configuration_error_context_and_http() -> None: ...
def test_connection_error_http_response() -> None: ...
def test_create_error_response_with_traceback() -> None: ...
def test_map_http_status_to_exception_specific(
    status: int, expected_type: type[FlextApiError]
) -> None: ...
def test_map_http_status_to_exception_ranges_and_default() -> None: ...
