class TestHttpMethod:
    def test_all_methods_available(self) -> None: ...
    def test_method_equality(self) -> None: ...
    def test_method_in_list(self) -> None: ...

class TestHttpStatus:
    def test_status_codes_values(self) -> None: ...
    def test_is_informational(self) -> None: ...
    def test_is_success(self) -> None: ...
    def test_is_redirection(self) -> None: ...
    def test_is_client_error(self) -> None: ...
    def test_is_server_error(self) -> None: ...

class TestURL:
    def test_create_success_https(self) -> None: ...
    def test_create_success_http(self) -> None: ...
    def test_create_success_with_query_and_fragment(self) -> None: ...
    def test_create_defaults_scheme_to_https(self) -> None: ...
    def test_create_empty_url_fails(self) -> None: ...
    def test_create_whitespace_url_fails(self) -> None: ...
    def test_create_invalid_scheme_fails(self) -> None: ...
    def test_create_no_host_fails(self) -> None: ...
    def test_create_invalid_port_fails(self) -> None: ...
    def test_create_zero_port_fails(self) -> None: ...
    def test_create_parsing_error_fails(self) -> None: ...
    def test_is_secure(self) -> None: ...
    def test_base_url_without_port(self) -> None: ...
    def test_base_url_with_port(self) -> None: ...
    def test_full_path_simple(self) -> None: ...
    def test_full_path_with_query(self) -> None: ...
    def test_full_path_with_fragment(self) -> None: ...
    def test_full_path_with_query_and_fragment(self) -> None: ...

class TestHttpHeader:
    def test_create_success(self) -> None: ...
    def test_create_authorization_header(self) -> None: ...
    def test_create_empty_name_fails(self) -> None: ...
    def test_create_whitespace_name_fails(self) -> None: ...
    def test_create_invalid_header_name_fails(self) -> None: ...
    def test_create_header_name_with_special_chars_fails(self) -> None: ...
    def test_create_valid_header_names_succeed(self) -> None: ...
    def test_create_control_character_in_value_fails(self) -> None: ...
    def test_create_tab_in_value_succeeds(self) -> None: ...
    def test_is_authorization(self) -> None: ...
    def test_is_authorization_case_insensitive(self) -> None: ...
    def test_is_content_type(self) -> None: ...
    def test_is_content_type_case_insensitive(self) -> None: ...
    def test_to_dict(self) -> None: ...
    def test_to_tuple(self) -> None: ...

class TestBearerToken:
    def test_create_success(self) -> None: ...
    def test_create_with_custom_type(self) -> None: ...
    def test_create_empty_token_fails(self) -> None: ...
    def test_create_whitespace_token_fails(self) -> None: ...
    def test_create_short_token_fails(self) -> None: ...
    def test_create_invalid_token_type_fails(self) -> None: ...
    def test_create_jwt_format_validation_success(self) -> None: ...
    def test_create_jwt_invalid_parts_fails(self) -> None: ...
    def test_create_jwt_empty_parts_fails(self) -> None: ...
    def test_is_jwt_format_true(self) -> None: ...
    def test_is_jwt_format_false(self) -> None: ...
    def test_to_authorization_header(self) -> None: ...
    def test_to_authorization_header_custom_type(self) -> None: ...
    def test_get_raw_token(self) -> None: ...
