import pytest

HTTP_OK: int

class TestAppCoverageComplete:
    def test_health_check_none_data_path(self) -> None: ...
    def test_health_check_with_data_path(self) -> None: ...
    def test_app_configuration(self) -> None: ...
    def test_app_has_health_endpoint(self) -> None: ...
    def test_health_endpoint_async_function(self) -> None: ...
    @pytest.mark.asyncio
    async def test_health_check_function_directly(self) -> None: ...
    def test_app_creation_multiple_times(self) -> None: ...
