class TestApiRequest:
    def test_basic_creation(self) -> None: ...
    def test_validation_success(self) -> None: ...
    def test_validation_empty_url_fails(self) -> None: ...
    def test_validation_whitespace_url_fails(self) -> None: ...
    def test_validation_invalid_url_scheme_fails(self) -> None: ...
    def test_validation_relative_path_succeeds(self) -> None: ...
    def test_validation_empty_header_key_fails(self) -> None: ...
    def test_validation_empty_header_value_fails(self) -> None: ...
    def test_start_processing_success(self) -> None: ...
    def test_start_processing_invalid_state_fails(self) -> None: ...
    def test_complete_processing_success(self) -> None: ...
    def test_complete_processing_invalid_state_fails(self) -> None: ...

class TestApiResponse:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_context(self) -> None: ...
    def test_validation_success(self) -> None: ...
    def test_validation_invalid_status_code_fails(self) -> None: ...
    def test_validation_high_status_code_fails(self) -> None: ...
    def test_validation_empty_header_key_fails(self) -> None: ...
    def test_validation_empty_header_value_fails(self) -> None: ...
    def test_mark_success(self) -> None: ...
    def test_mark_error(self) -> None: ...

class TestApiEndpoint:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_full_context(self) -> None: ...
    def test_validation_success(self) -> None: ...
    def test_validation_empty_path_fails(self) -> None: ...
    def test_validation_path_without_slash_fails(self) -> None: ...
    def test_validation_empty_methods_fails(self) -> None: ...
    def test_validation_negative_rate_limit_fails(self) -> None: ...
    def test_validation_zero_rate_limit_fails(self) -> None: ...
    def test_supports_method(self) -> None: ...
    def test_requires_authentication(self) -> None: ...

class TestApiSession:
    def test_basic_creation(self) -> None: ...
    def test_creation_with_context(self) -> None: ...
    def test_validation_success(self) -> None: ...
    def test_validation_short_token_fails(self) -> None: ...
    def test_validation_past_expiration_fails(self) -> None: ...
    def test_is_expired_no_expiration(self) -> None: ...
    def test_is_expired_future_expiration(self) -> None: ...
    def test_is_expired_past_expiration(self) -> None: ...
    def test_extend_session_success(self) -> None: ...
    def test_extend_session_custom_duration(self) -> None: ...
    def test_extend_inactive_session_fails(self) -> None: ...
    def test_deactivate_session(self) -> None: ...
