EXPECTED_DATA_COUNT: int

class TestConstants:
    def test_version_constant(self) -> None: ...
    def test_timeout_constant(self) -> None: ...
    def test_retries_constant(self) -> None: ...
    def test_cache_ttl_constant(self) -> None: ...

class TestFlextApiConstants:
    def test_success_codes(self) -> None: ...
    def test_client_error_codes(self) -> None: ...
    def test_server_error_codes(self) -> None: ...
    def test_rate_limit_constants(self) -> None: ...
    def test_response_templates(self) -> None: ...

class TestFlextApiFieldType:
    def test_field_types(self) -> None: ...
    def test_field_type_validation(self) -> None: ...

class TestFlextApiStatus:
    def test_request_status(self) -> None: ...
    def test_service_status(self) -> None: ...
    def test_pipeline_status(self) -> None: ...
    def test_plugin_status(self) -> None: ...

class TestFlextApiEndpoints:
    def test_base_paths(self) -> None: ...
    def test_auth_endpoints(self) -> None: ...
    def test_pipeline_endpoints(self) -> None: ...
    def test_plugin_endpoints(self) -> None: ...
