import pytest

def test_request_method_conversion_and_to_dict() -> None: ...
@pytest.mark.asyncio
async def test_caching_plugin_cache_hit_path() -> None: ...
@pytest.mark.asyncio
async def test_perform_http_request_no_session(
    monkeypatch: pytest.MonkeyPatch,
) -> None: ...
def test_build_stub_response_status_nonint() -> None: ...
@pytest.mark.asyncio
async def test_process_response_pipeline_none_response() -> None: ...
def test_response_builder_with_metadata_key_requires_value() -> None: ...
