class TestInitCoverage:
    def test_version_import_success(self) -> None: ...
    def test_version_import_fallback(self) -> None: ...
    def test_version_info_generation(self) -> None: ...
    def test_all_imports_successful(self) -> None: ...
    def test_all_list_completeness(self) -> None: ...
    def test_version_fallback(self) -> None: ...
    def test_version_attributes_exist(self) -> None: ...
    def test_flext_core_imports_work(self) -> None: ...
