class TestFlextApiSettings:
    def test_settings_creation_defaults(self) -> None: ...
    def test_settings_creation_with_values(self) -> None: ...
    def test_port_validation_valid_port(self) -> None: ...
    def test_port_validation_invalid_port_zero(self) -> None: ...
    def test_port_validation_invalid_port_negative(self) -> None: ...
    def test_port_validation_invalid_port_too_high(self) -> None: ...
    def test_port_validator_method_directly(self) -> None: ...
    def test_api_workers_validation(self) -> None: ...
    def test_default_timeout_validation(self) -> None: ...
    def test_max_retries_validation(self) -> None: ...
    def test_cache_ttl_validation(self) -> None: ...
    def test_environment_variables_integration(self) -> None: ...
    def test_settings_serialization(self) -> None: ...

class TestCreateApiSettingsFactory:
    def test_create_api_settings_no_overrides(self) -> None: ...
    def test_create_api_settings_with_valid_overrides(self) -> None: ...
    def test_create_api_settings_with_invalid_overrides(self) -> None: ...
    def test_create_api_settings_with_invalid_port_validation(self) -> None: ...
    def test_create_api_settings_mixed_valid_invalid(self) -> None: ...
    def test_create_api_settings_empty_dict_override(self) -> None: ...
    def test_create_api_settings_type_conversion(self) -> None: ...
    def test_create_api_settings_return_type_verification(self) -> None: ...

class TestFlextApiSettingsIntegration:
    def test_flext_base_settings_inheritance(self) -> None: ...
    def test_create_with_validation_method(self) -> None: ...
    def test_create_with_validation_failure(self) -> None: ...
    def test_config_env_prefix(self) -> None: ...
    def test_field_descriptions(self) -> None: ...
