import pytest

def test_run_development_server_invokes_uvicorn(
    monkeypatch: pytest.MonkeyPatch,
) -> None: ...
def test_run_production_server_invokes_uvicorn(
    monkeypatch: pytest.MonkeyPatch,
) -> None: ...
def test_create_flext_api_app_with_settings_success() -> None: ...
def test_create_flext_api_app_with_settings_failure(
    monkeypatch: pytest.MonkeyPatch,
) -> None: ...
def test_main_entrypoint_smoke(monkeypatch: pytest.MonkeyPatch) -> None: ...
