import pytest

def test_public_sync_health_check_and_helpers() -> None: ...
@pytest.mark.asyncio
async def test_storage_set_get_via_factory() -> None: ...
def test_deprecated_create_api_service_and_client_paths() -> None: ...
@pytest.mark.asyncio
async def test__create_client_impl_failure_and_success() -> None: ...
def test_app_health_storage_error_and_nonawaitable_paths() -> None: ...
def test_app_error_fallback_route_via_env(monkeypatch: pytest.MonkeyPatch) -> None: ...
