import pytest

@pytest.mark.asyncio
async def test_memory_backend_ttl_and_keys() -> None: ...
@pytest.mark.asyncio
async def test_file_backend_persistence_roundtrip(tmp_path: object) -> None: ...
def test_memory_cache_basic() -> None: ...
@pytest.mark.asyncio
async def test_flext_storage_namespace_and_transactions() -> None: ...
@pytest.mark.asyncio
async def test_flext_storage_keys_and_clear() -> None: ...
