EXPECTED_BULK_SIZE: int

class TestFlextApiQuery:
    def test_query_creation(self) -> None: ...
    def test_query_with_custom_values(self) -> None: ...
    def test_query_validation_negative_page(self) -> None: ...
    def test_query_validation_negative_page_size(self) -> None: ...
    def test_query_to_dict(self) -> None: ...

class TestFlextApiResponse:
    def test_response_creation(self) -> None: ...
    def test_response_with_data(self) -> None: ...
    def test_response_to_dict(self) -> None: ...

class TestFlextApiQueryBuilder:
    def test_query_builder_creation(self) -> None: ...
    def test_equals_filter(self) -> None: ...
    def test_greater_than_filter(self) -> None: ...
    def test_sort_desc(self) -> None: ...
    def test_sort_asc(self) -> None: ...
    def test_pagination(self) -> None: ...
    def test_pagination_validation(self) -> None: ...
    def test_empty_field_validation(self) -> None: ...
    def test_chained_operations(self) -> None: ...

class TestFlextApiResponseBuilder:
    def test_response_builder_creation(self) -> None: ...
    def test_success_response(self) -> None: ...
    def test_error_response(self) -> None: ...
    def test_with_metadata(self) -> None: ...
    def test_with_pagination(self) -> None: ...
    def test_pagination_validation(self) -> None: ...

class TestFactoryFunctions:
    def test_build_query(self) -> None: ...
    def test_build_query_empty(self) -> None: ...
    def test_build_success_response(self) -> None: ...
    def test_build_error_response(self) -> None: ...
    def test_build_paginated_response(self) -> None: ...

class TestFlextApiBuilder:
    def test_builder_creation(self) -> None: ...
    def test_for_query(self) -> None: ...
    def test_for_response(self) -> None: ...
