class TestFlextAPIFieldCore:
    def test_api_key_field_creation(self) -> None: ...
    def test_api_key_field_with_description(self) -> None: ...
    def test_bearer_token_field_creation(self) -> None: ...
    def test_bearer_token_field_with_description(self) -> None: ...
    def test_pipeline_config_field_creation(self) -> None: ...
    def test_pipeline_config_field_with_description(self) -> None: ...
    def test_plugin_config_field_creation(self) -> None: ...
    def test_plugin_config_field_with_description(self) -> None: ...
    def test_user_role_field_creation(self) -> None: ...
    def test_user_role_field_with_description(self) -> None: ...
    def test_endpoint_path_field_creation(self) -> None: ...
    def test_endpoint_path_field_with_description(self) -> None: ...
    def test_http_method_field_creation(self) -> None: ...
    def test_http_method_field_with_description(self) -> None: ...
    def test_response_format_field_creation(self) -> None: ...
    def test_response_format_field_with_description(self) -> None: ...
    def test_field_creation_with_kwargs(self) -> None: ...

class TestFlextAPIFields:
    def test_authentication_fields_exist(self) -> None: ...
    def test_configuration_fields_exist(self) -> None: ...
    def test_authorization_fields_exist(self) -> None: ...
    def test_api_fields_exist(self) -> None: ...
    def test_user_management_fields_exist(self) -> None: ...
    def test_pipeline_fields_exist(self) -> None: ...
    def test_plugin_fields_exist(self) -> None: ...
    def test_system_fields_exist(self) -> None: ...
    def test_request_response_fields_exist(self) -> None: ...

class TestConvenienceFieldBuilders:
    def test_api_key_field_function(self) -> None: ...
    def test_api_key_field_function_with_description(self) -> None: ...
    def test_bearer_token_field_function(self) -> None: ...
    def test_bearer_token_field_function_with_description(self) -> None: ...
    def test_pipeline_config_field_function(self) -> None: ...
    def test_pipeline_config_field_function_with_description(self) -> None: ...
    def test_plugin_config_field_function(self) -> None: ...
    def test_plugin_config_field_function_with_description(self) -> None: ...
    def test_user_role_field_function(self) -> None: ...
    def test_user_role_field_function_with_description(self) -> None: ...
    def test_endpoint_path_field_function(self) -> None: ...
    def test_endpoint_path_field_function_with_description(self) -> None: ...
    def test_http_method_field_function(self) -> None: ...
    def test_http_method_field_function_with_description(self) -> None: ...
    def test_response_format_field_function(self) -> None: ...
    def test_response_format_field_function_with_description(self) -> None: ...
    def test_field_function_with_kwargs(self) -> None: ...

class TestFieldsModuleIntegration:
    def test_field_core_and_function_consistency(self) -> None: ...
    def test_all_convenience_functions_work(self) -> None: ...
    def test_fields_class_attributes_are_valid(self) -> None: ...
    def test_type_annotations_coverage(self) -> None: ...
