def example_query_builder() -> None: ...
def example_response_builder() -> None: ...
def example_fastapi_builder() -> None: ...
async def example_http_client() -> None: ...
def example_integration() -> None: ...
async def main() -> None: ...
