def example_query_builder() -> None: ...
def example_response_builder() -> None: ...
def example_factory_functions() -> None: ...
async def example_api_service() -> None: ...
async def example_http_client() -> None: ...
def example_fastapi_app() -> None: ...
def example_main_builder() -> None: ...
async def main() -> None: ...
