"""Temporary minimal protocols for fixing import issues."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Protocol

from flext_core import FlextResult

# Minimal protocol definitions to fix imports
class FlextApiAuthProtocol(Protocol):
    async def authenticate(self, credentials: dict[str, Any]) -> FlextResult[str]: ...

class FlextApiAuthorizationProtocol(Protocol):  
    async def authorize(self, user_id: str, resource: str) -> FlextResult[bool]: ...

class FlextApiCacheProtocol(Protocol):
    async def get(self, key: str) -> FlextResult[Any]: ...
    async def set(self, key: str, value: Any, ttl: int = 300) -> FlextResult[None]: ...

class FlextApiConnectionPoolProtocol(Protocol):
    async def get_connection(self) -> FlextResult[Any]: ...

class FlextApiHandlerProtocol(Protocol):
    async def handle(self, request: Any) -> FlextResult[Any]: ...

class FlextApiHealthCheckProtocol(Protocol):
    async def check_health(self) -> FlextResult[dict[str, Any]]: ...

class FlextApiMetricsProtocol(Protocol):
    async def record_metric(self, name: str, value: float) -> None: ...

class FlextApiMiddlewareProtocol(Protocol):
    async def process(self, request: Any, next_handler: Any) -> FlextResult[Any]: ...

class FlextApiPluginProtocol(Protocol):
    async def before_request(self, request: Any) -> Any: ...
    async def after_request(self, request: Any, response: Any) -> None: ...

class FlextApiQueryBuilderProtocol(Protocol):
    def build(self) -> Any: ...

class FlextApiRateLimitProtocol(Protocol):
    async def check_rate_limit(self, key: str) -> FlextResult[bool]: ...

class FlextApiRepositoryProtocol(Protocol):
    async def find_by_id(self, id: str) -> FlextResult[Any]: ...

class FlextApiResponseBuilderProtocol(Protocol):
    def build(self) -> Any: ...

class FlextApiServiceProtocol(Protocol):
    async def execute(self, request: Any) -> FlextResult[Any]: ...

class FlextApiStreamProtocol(Protocol):
    async def stream(self) -> Any: ...

class FlextApiValidatorProtocol(Protocol):
    async def validate(self, data: Any) -> FlextResult[bool]: ...

class FlextApiWebSocketProtocol(Protocol):
    async def send(self, message: str) -> None: ...

class FlextApiClientProtocol(Protocol):
    async def request(self, method: str, url: str, **kwargs: Any) -> FlextResult[Any]: ...