import asyncio
from collections.abc import AsyncGenerator, Callable as Callable, Iterator
from pathlib import Path
from unittest.mock import AsyncMock

import pytest
from _typeshed import Incomplete
from fastapi.testclient import TestClient

fake: Incomplete

def pytest_sessionstart(session: pytest.Session) -> None: ...
def pytest_runtest_setup(item: pytest.Item) -> None: ...
@pytest.fixture
def project_root() -> Path: ...
@pytest.fixture
def set_test_environment() -> None: ...
@pytest.fixture
def sample_api_config() -> dict[str, object]: ...
@pytest.fixture
def sample_pipeline_data() -> dict[str, object]: ...
@pytest.fixture
def sample_plugin_data() -> dict[str, object]: ...
@pytest.fixture
def sample_user_data() -> dict[str, object]: ...
@pytest.fixture
def mock_auth_service() -> AsyncMock: ...
@pytest.fixture
def mock_pipeline_repository() -> AsyncMock: ...
@pytest.fixture
def mock_plugin_service() -> AsyncMock: ...
@pytest.fixture
async def api_client() -> AsyncGenerator[TestClient]: ...
def reset_storage() -> None: ...
@pytest.fixture
def auth_headers() -> dict[str, str]: ...
@pytest.fixture
async def cleanup_client_sessions() -> AsyncGenerator[None]: ...
def sync_cleanup_client_sessions() -> None: ...
def pytest_configure(config: pytest.Config) -> None: ...
def pytest_collection_modifyitems(items: list[pytest.Item]) -> None: ...
def event_loop() -> Iterator[asyncio.AbstractEventLoop]: ...
def optimize_test_performance() -> None: ...
@pytest.fixture
def benchmark() -> Callable[[Callable[..., object]], object]: ...
