import dataclasses

from _typeshed import Incomplete
from flext_core import FlextResult as FlextResult, get_logger as get_logger

from flext_api.api import FlextApi as FlextApi, create_flext_api as create_flext_api
from flext_api.api_app import (
    app as app,
    create_flext_api_app as create_flext_api_app,
    create_flext_api_app_with_settings as create_flext_api_app_with_settings,
    run_development_server as run_development_server,
    run_production_server as run_production_server,
)
from flext_api.api_client import (
    FlextApiBuilder as FlextApiBuilder,
    FlextApiCachingPlugin as FlextApiCachingPlugin,
    FlextApiClient as FlextApiClient,
    FlextApiClientConfig as FlextApiClientConfig,
    FlextApiClientMethod as FlextApiClientMethod,
    FlextApiClientProtocol as FlextApiClientProtocol,
    FlextApiClientRequest as FlextApiClientRequest,
    FlextApiClientResponse as FlextApiClientResponse,
    FlextApiClientStatus as FlextApiClientStatus,
    FlextApiOperation as FlextApiOperation,
    FlextApiPlugin as FlextApiPlugin,
    FlextApiQuery as FlextApiQuery,
    FlextApiQueryBuilder as FlextApiQueryBuilder,
    FlextApiResponse as FlextApiResponse,
    FlextApiResponseBuilder as FlextApiResponseBuilder,
    FlextApiRetryPlugin as FlextApiRetryPlugin,
    PaginatedResponseBuilder as PaginatedResponseBuilder,
    PaginationConfig as PaginationConfig,
    ResponseConfig as ResponseConfig,
    build_error_response as build_error_response,
    build_paginated_response as build_paginated_response,
    build_query as build_query,
    build_query_from_params as build_query_from_params,
    build_success_response as build_success_response,
    create_client as create_client,
)
from flext_api.api_config import (
    FlextApiSettings as FlextApiSettings,
    create_api_settings as create_api_settings,
    load_configuration as load_configuration,
    validate_configuration as validate_configuration,
)
from flext_api.api_exceptions import (
    FlextApiAuthenticationError as FlextApiAuthenticationError,
    FlextApiAuthorizationError as FlextApiAuthorizationError,
    FlextApiBuilderError as FlextApiBuilderError,
    FlextApiConfigurationError as FlextApiConfigurationError,
    FlextApiConnectionError as FlextApiConnectionError,
    FlextApiError as FlextApiError,
    FlextApiNotFoundError as FlextApiNotFoundError,
    FlextApiProcessingError as FlextApiProcessingError,
    FlextApiRateLimitError as FlextApiRateLimitError,
    FlextApiRequestError as FlextApiRequestError,
    FlextApiResponseError as FlextApiResponseError,
    FlextApiStorageError as FlextApiStorageError,
    FlextApiTimeoutError as FlextApiTimeoutError,
    FlextApiValidationError as FlextApiValidationError,
    create_error_response as create_error_response,
    map_http_status_to_exception as map_http_status_to_exception,
)
from flext_api.api_models import (
    DEFAULT_MAX_RETRIES as DEFAULT_MAX_RETRIES,
    DEFAULT_PAGE_SIZE as DEFAULT_PAGE_SIZE,
    DEFAULT_TIMEOUT as DEFAULT_TIMEOUT,
    URL as URL,
    ApiEndpoint as ApiEndpoint,
    ApiErrorContext as ApiErrorContext,
    ApiRequest as ApiRequest,
    ApiResponse as ApiResponse,
    ApiSession as ApiSession,
    BearerToken as BearerToken,
    ClientConfig as ClientConfig,
    ClientProtocol as ClientProtocol,
    ClientStatus as ClientStatus,
    HttpHeader as HttpHeader,
    HttpMethod as HttpMethod,
    HttpStatus as HttpStatus,
    OperationType as OperationType,
    PaginationInfo as PaginationInfo,
    QueryBuilder as QueryBuilder,
    QueryConfig as QueryConfig,
    RequestDto as RequestDto,
    RequestState as RequestState,
    ResponseBuilder as ResponseBuilder,
    ResponseDto as ResponseDto,
    ResponseState as ResponseState,
    TokenType as TokenType,
)
from flext_api.api_protocols import (
    FlextApiAuthorizationProtocol as FlextApiAuthorizationProtocol,
    FlextApiAuthProtocol as FlextApiAuthProtocol,
    FlextApiCacheProtocol as FlextApiCacheProtocol,
    FlextApiConnectionPoolProtocol as FlextApiConnectionPoolProtocol,
    FlextApiHandlerProtocol as FlextApiHandlerProtocol,
    FlextApiHealthCheckProtocol as FlextApiHealthCheckProtocol,
    FlextApiMetricsProtocol as FlextApiMetricsProtocol,
    FlextApiMiddlewareProtocol as FlextApiMiddlewareProtocol,
    FlextApiPluginProtocol as FlextApiPluginProtocol,
    FlextApiQueryBuilderProtocol as FlextApiQueryBuilderProtocol,
    FlextApiRateLimitProtocol as FlextApiRateLimitProtocol,
    FlextApiRepositoryProtocol as FlextApiRepositoryProtocol,
    FlextApiResponseBuilderProtocol as FlextApiResponseBuilderProtocol,
    FlextApiServiceProtocol as FlextApiServiceProtocol,
    FlextApiStreamProtocol as FlextApiStreamProtocol,
    FlextApiValidatorProtocol as FlextApiValidatorProtocol,
    FlextApiWebSocketProtocol as FlextApiWebSocketProtocol,
)
from flext_api.api_storage import (
    FileStorageBackend as FileStorageBackend,
    FlextApiStorage as FlextApiStorage,
    MemoryCache as MemoryCache,
    MemoryStorageBackend as MemoryStorageBackend,
    StorageBackend as StorageBackend,
    StorageConfig as StorageConfig,
    create_file_storage as create_file_storage,
    create_memory_storage as create_memory_storage,
    create_storage as create_storage,
)
from flext_api.api_types import (
    APITypes as APITypes,
    APITypesCompat as APITypesCompat,
    FlextAPIFieldCore as FlextAPIFieldCore,
    FlextAPIFields as FlextAPIFields,
    T_Payload as T_Payload,
    T_Request as T_Request,
    T_Response as T_Response,
    TData as TData,
    api_key_field as api_key_field,
    bearer_token_field as bearer_token_field,
    endpoint_path_field as endpoint_path_field,
    get_api_types as get_api_types,
    http_method_field as http_method_field,
    pipeline_config_field as pipeline_config_field,
    plugin_config_field as plugin_config_field,
    response_format_field as response_format_field,
    user_role_field as user_role_field,
)
from flext_api.app import flext_api_create_app as flext_api_create_app
from flext_api.base_service import (
    FlextApiBaseAuthService as FlextApiBaseAuthService,
    FlextApiBaseBuilderService as FlextApiBaseBuilderService,
    FlextApiBaseClientService as FlextApiBaseClientService,
    FlextApiBaseHandlerService as FlextApiBaseHandlerService,
    FlextApiBaseRepositoryService as FlextApiBaseRepositoryService,
    FlextApiBaseService as FlextApiBaseService,
    FlextApiBaseStreamingService as FlextApiBaseStreamingService,
)
from flext_api.client import create_client_with_plugins as create_client_with_plugins
from flext_api.constants import FlextApiConstants as FlextApiConstants

__all__ = [
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_PAGE_SIZE",
    "DEFAULT_TIMEOUT",
    "FLEXT_API_CACHE_TTL",
    "FLEXT_API_MAX_RETRIES",
    "FLEXT_API_TIMEOUT",
    "FLEXT_API_VERSION",
    "URL",
    "APITypes",
    "APITypesCompat",
    "ApiEndpoint",
    "ApiErrorContext",
    "ApiRequest",
    "ApiResponse",
    "ApiSession",
    "BearerToken",
    "ClientConfig",
    "ClientProtocol",
    "ClientStatus",
    "FileStorageBackend",
    "FlextAPIFieldCore",
    "FlextAPIFields",
    "FlextApi",
    "FlextApiAuthProtocol",
    "FlextApiAuthenticationError",
    "FlextApiAuthorizationError",
    "FlextApiAuthorizationProtocol",
    "FlextApiBaseAuthService",
    "FlextApiBaseBuilderService",
    "FlextApiBaseClientService",
    "FlextApiBaseHandlerService",
    "FlextApiBaseRepositoryService",
    "FlextApiBaseService",
    "FlextApiBaseStreamingService",
    "FlextApiBuilder",
    "FlextApiBuilderError",
    "FlextApiCacheProtocol",
    "FlextApiCachingPlugin",
    "FlextApiClient",
    "FlextApiClientConfig",
    "FlextApiClientMethod",
    "FlextApiClientProtocol",
    "FlextApiClientRequest",
    "FlextApiClientResponse",
    "FlextApiClientStatus",
    "FlextApiConfigurationError",
    "FlextApiConnectionError",
    "FlextApiConnectionPoolProtocol",
    "FlextApiConstants",
    "FlextApiError",
    "FlextApiHandlerProtocol",
    "FlextApiHealthCheckProtocol",
    "FlextApiMetricsProtocol",
    "FlextApiMiddlewareProtocol",
    "FlextApiNotFoundError",
    "FlextApiOperation",
    "FlextApiPlugin",
    "FlextApiPluginProtocol",
    "FlextApiProcessingError",
    "FlextApiQuery",
    "FlextApiQueryBuilder",
    "FlextApiQueryBuilderProtocol",
    "FlextApiRateLimitError",
    "FlextApiRateLimitProtocol",
    "FlextApiRepositoryProtocol",
    "FlextApiRequestError",
    "FlextApiResponse",
    "FlextApiResponseBuilder",
    "FlextApiResponseBuilderProtocol",
    "FlextApiResponseError",
    "FlextApiRetryPlugin",
    "FlextApiServiceProtocol",
    "FlextApiSettings",
    "FlextApiStorage",
    "FlextApiStorageError",
    "FlextApiStreamProtocol",
    "FlextApiTimeoutError",
    "FlextApiValidationError",
    "FlextApiValidatorProtocol",
    "FlextApiWebSocketProtocol",
    "FlextResult",
    "HttpHeader",
    "HttpMethod",
    "HttpStatus",
    "MemoryCache",
    "MemoryStorageBackend",
    "OperationType",
    "PaginatedResponseBuilder",
    "PaginationConfig",
    "PaginationInfo",
    "QueryBuilder",
    "QueryConfig",
    "RequestDto",
    "RequestState",
    "ResponseBuilder",
    "ResponseConfig",
    "ResponseDto",
    "ResponseState",
    "StorageBackend",
    "StorageConfig",
    "TData",
    "T_Payload",
    "T_Request",
    "T_Response",
    "TokenType",
    "__version__",
    "__version_info__",
    "api_key_field",
    "app",
    "bearer_token_field",
    "build_error_response",
    "build_paginated_response",
    "build_query",
    "build_query_dict",
    "build_query_from_params",
    "build_success_response",
    "create_api_builder",
    "create_api_client",
    "create_api_settings",
    "create_api_storage",
    "create_client",
    "create_client_with_plugins",
    "create_error_response",
    "create_file_storage",
    "create_flext_api",
    "create_flext_api_app",
    "create_flext_api_app_with_settings",
    "create_memory_storage",
    "create_storage",
    "endpoint_path_field",
    "flext_api_create_app",
    "get_api_types",
    "get_logger",
    "http_method_field",
    "load_configuration",
    "map_http_status_to_exception",
    "pipeline_config_field",
    "plugin_config_field",
    "response_format_field",
    "run_development_server",
    "run_production_server",
    "sync_health_check",
    "user_role_field",
    "validate_configuration",
]

__version__: Incomplete
__version_info__: Incomplete

@dataclasses.dataclass
class FlextApiQueryParameters:
    filters: dict[str, object] | list[dict[str, object]] | None = ...
    sorts: list[dict[str, str]] | None = ...
    page: int = ...
    page_size: int = ...
    search: str | None = ...
    fields: list[str] | None = ...

def build_query_dict(
    filters: dict[str, object] | None = None,
    sorts: list[dict[str, str]] | None = None,
    page: int = 1,
    page_size: int = 20,
    search: str | None = None,
    fields: list[str] | None = None,
) -> dict[str, object]: ...
def sync_health_check(api: FlextApi) -> FlextResult[dict[str, object]]: ...

FLEXT_API_TIMEOUT: Incomplete
FLEXT_API_MAX_RETRIES: Incomplete
FLEXT_API_CACHE_TTL: Incomplete
FLEXT_API_VERSION = __version__

def create_api_client(config: dict[str, object] | None = None) -> FlextApiClient: ...
def create_api_builder() -> FlextApiBuilder: ...
def create_api_storage(
    backend: str = "memory", **kwargs: object
) -> FlextApiStorage: ...

# Names in __all__ with no definition:
#   annotations
