from flext_core import FlextResult

from flext_api.api_client import FlextApiBuilder, FlextApiClient
from flext_api.api_protocols import (
    FlextApiClientProtocol,
    FlextApiQueryBuilderProtocol,
    FlextApiResponseBuilderProtocol,
)
from flext_api.base_service import FlextApiBaseService
from flext_api.typings import FlextTypes

__all__ = ["FlextApi", "create_api_service", "create_flext_api"]

class FlextApi(FlextApiBaseService):
    service_name: str
    service_version: str = ...
    def __init__(self, **_data: object) -> None: ...
    async def health_check(self) -> FlextResult[FlextTypes.Core.JsonDict]: ...
    def sync_health_check(self) -> FlextResult[dict[str, object]]: ...
    def health_check_sync(self) -> FlextResult[dict[str, object]]: ...
    def create_client(
        self, config: dict[str, object] | None = None
    ) -> FlextResult[FlextApiClientProtocol]: ...
    def get_builder(self) -> FlextApiBuilder: ...
    def get_query_builder(self) -> FlextApiQueryBuilderProtocol: ...
    def get_response_builder(self) -> FlextApiResponseBuilderProtocol: ...
    def get_client(self) -> FlextApiClientProtocol | None: ...
    def get_service_info(self) -> FlextTypes.Core.JsonDict: ...
    def flext_api_create_client(
        self, config: FlextTypes.Core.JsonDict | None = None
    ) -> FlextResult[FlextApiClient]: ...

def create_flext_api(**config: object) -> FlextApi: ...
def create_api_service() -> FlextApi: ...
