from dataclasses import dataclass
from enum import Enum, StrEnum
from typing import Self

from _typeshed import Incomplete
from flext_core import FlextResult, FlextTypes

__all__ = [
    "FlextApiBuilder",
    "FlextApiCachingPlugin",
    "FlextApiClient",
    "FlextApiClientConfig",
    "FlextApiClientMethod",
    "FlextApiClientProtocol",
    "FlextApiClientRequest",
    "FlextApiClientResponse",
    "FlextApiClientStatus",
    "FlextApiOperation",
    "FlextApiPlugin",
    "FlextApiQuery",
    "FlextApiQueryBuilder",
    "FlextApiResponse",
    "FlextApiResponseBuilder",
    "FlextApiRetryPlugin",
    "PaginatedResponseBuilder",
    "PaginationConfig",
    "ResponseConfig",
    "build_error_response",
    "build_paginated_response",
    "build_query",
    "build_success_response",
    "create_client",
]

class FlextApiClientProtocol(StrEnum):
    HTTP = "http"
    HTTPS = "https"

class FlextApiClientMethod(StrEnum):
    GET = ...
    POST = ...
    PUT = ...
    DELETE = ...
    PATCH = ...
    HEAD = ...
    OPTIONS = ...

class FlextApiClientStatus(StrEnum):
    IDLE = "idle"
    ACTIVE = "active"
    RUNNING = "running"
    STOPPED = "stopped"
    CLOSED = "closed"
    ERROR = "error"

@dataclass(frozen=True)
class FlextApiClientConfig:
    base_url: str = ...
    timeout: float = ...
    headers: dict[str, str] = ...
    max_retries: int = ...
    plugins: list[FlextApiPlugin] = ...
    verify_ssl: bool = ...
    follow_redirects: bool = ...
    def __post_init__(self) -> None: ...

@dataclass(frozen=True)
class FlextApiClientRequest:
    method: str | FlextApiClientMethod
    url: str
    headers: dict[str, str] = ...
    params: FlextTypes.Core.JsonDict | None = ...
    json_data: FlextTypes.Core.JsonDict | None = ...
    data: str | bytes | None = ...
    timeout: float | None = ...
    def __post_init__(self) -> None: ...
    def to_dict(self) -> FlextTypes.Core.JsonDict: ...

@dataclass(frozen=True)
class FlextApiClientResponse:
    status_code: int
    headers: dict[str, str] = ...
    data: FlextTypes.Core.JsonDict | list[object] | str | bytes | None = ...
    elapsed_time: float = ...
    request_id: str | None = ...
    from_cache: bool = ...
    def is_success(self) -> bool: ...
    def is_error(self) -> bool: ...
    def json(self) -> object: ...
    def text(self) -> str: ...

@dataclass(frozen=True)
class ResponseConfig:
    success: bool | None = ...
    data: object = ...
    message: str | None = ...
    metadata: FlextTypes.Core.JsonDict | None = ...
    pagination: FlextTypes.Core.JsonDict | None = ...

@dataclass(frozen=True)
class PaginationConfig:
    data: object
    total: int
    page: int
    page_size: int
    message: str = ...
    metadata: FlextTypes.Core.JsonDict | None = ...
    def __post_init__(self) -> None: ...

class FlextApiOperation(Enum):
    QUERY = "query"
    RESPONSE = "response"

@dataclass(frozen=True)
class FlextApiQuery:
    filters: list[FlextTypes.Core.JsonDict] = ...
    sorts: list[dict[str, str]] = ...
    page: int = ...
    page_size: int = ...
    search: str | None = ...
    fields: list[str] | None = ...
    includes: list[str] | None = ...
    excludes: list[str] | None = ...
    def __post_init__(self) -> None: ...
    def to_dict(self) -> FlextTypes.Core.JsonDict: ...

@dataclass(frozen=True)
class FlextApiResponse:
    success: bool = ...
    data: object = ...
    message: str = ...
    errors: list[str] | None = ...
    metadata: FlextTypes.Core.JsonDict = ...
    pagination: FlextTypes.Core.JsonDict | None = ...
    status_code: int = ...
    timestamp: str = ...
    def to_dict(self) -> FlextTypes.Core.JsonDict: ...
    def __getitem__(self, key: str | int) -> object: ...
    def __setitem__(self, key: str, value: object) -> None: ...
    def __contains__(self, key: object) -> bool: ...

class FlextApiPlugin:
    name: Incomplete
    enabled: Incomplete
    def __init__(self, name: str | None = None, *, enabled: bool = True) -> None: ...
    async def before_request(
        self, request: FlextApiClientRequest, _context: dict[str, object] | None = None
    ) -> object: ...
    async def after_response(
        self,
        response: FlextApiClientResponse,
        _context: dict[str, object] | None = None,
    ) -> object: ...
    async def after_request(self, _request: object, response: object) -> object: ...
    async def on_error(self, _request: object, error: object) -> object: ...
    def get_info(self) -> dict[str, object]: ...

class FlextApiCachingPlugin(FlextApiPlugin):
    ttl: Incomplete
    max_size: Incomplete
    def __init__(self, ttl: int = 300, max_size: int = 1000) -> None: ...
    async def before_request(
        self, request: object, _context: object = None
    ) -> object: ...
    async def after_response(
        self, response: object, _context: object = None
    ) -> object: ...

class FlextApiRetryPlugin(FlextApiPlugin):
    max_retries: Incomplete
    backoff_factor: Incomplete
    def __init__(self, max_retries: int = 3, backoff_factor: float = 2.0) -> None: ...

class FlextApiClient:
    def __init__(
        self,
        config: FlextApiClientConfig | None = None,
        plugins: list[FlextApiPlugin] | None = None,
    ) -> None: ...
    def health_check(self) -> dict[str, str]: ...
    async def start(self) -> FlextResult[None]: ...
    async def stop(self) -> FlextResult[None]: ...
    @property
    def config(self) -> FlextApiClientConfig: ...
    @property
    def status(self) -> FlextApiClientStatus: ...
    @property
    def plugins(self) -> list[FlextApiPlugin]: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(
        self, exc_type: object, exc_val: object, exc_tb: object
    ) -> None: ...
    async def close(self) -> None: ...
    async def get(
        self,
        path: str,
        params: FlextTypes.Core.JsonDict | None = None,
        headers: dict[str, str] | None = None,
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def post(
        self,
        path: str,
        json_data: FlextTypes.Core.JsonDict | None = None,
        data: str | bytes | None = None,
        headers: dict[str, str] | None = None,
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def put(
        self,
        path: str,
        json_data: FlextTypes.Core.JsonDict | None = None,
        data: str | bytes | None = None,
        headers: dict[str, str] | None = None,
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def patch(
        self,
        path: str,
        json_data: FlextTypes.Core.JsonDict | None = None,
        data: str | bytes | None = None,
        headers: dict[str, str] | None = None,
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def delete(
        self, path: str, headers: dict[str, str] | None = None
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def head(
        self, path: str, headers: dict[str, str] | None = None
    ) -> FlextResult[FlextApiClientResponse]: ...
    async def options(
        self, path: str, headers: dict[str, str] | None = None
    ) -> FlextResult[FlextApiClientResponse]: ...

class FlextApiBuilder:
    def for_query(self) -> FlextApiQueryBuilder: ...
    def for_response(self) -> FlextApiResponseBuilder: ...

class FlextApiQueryBuilder:
    def __init__(self) -> None: ...
    def with_filters(self, filters: FlextTypes.Core.JsonDict) -> Self: ...
    def with_sorting(self, sorts: list[dict[str, str]]) -> Self: ...
    def with_pagination(self, page: int, page_size: int) -> Self: ...
    def with_search(self, search: str) -> Self: ...
    def with_fields(self, fields: list[str]) -> Self: ...
    def equals(self, field: str, value: object) -> Self: ...
    def greater_than(self, field: str, value: object) -> Self: ...
    def sort_desc(self, field: str) -> Self: ...
    def sort_asc(self, field: str) -> Self: ...
    def page(self, page: int) -> Self: ...
    def page_size(self, size: int) -> Self: ...
    def pagination(self, page: int, size: int) -> Self: ...
    def build(self) -> FlextApiQuery: ...

class FlextApiResponseBuilder:
    def __init__(self) -> None: ...
    def with_success_data(self, data: object) -> Self: ...
    def with_error_data(self, error: str, status_code: int = 400) -> Self: ...
    def with_message(self, message: str) -> Self: ...
    def with_metadata(
        self, metadata: FlextTypes.Core.JsonDict | str, value: object | None = None
    ) -> Self: ...
    def with_pagination(
        self,
        pagination: FlextTypes.Core.JsonDict | None = None,
        *,
        total: int | None = None,
        page: int | None = None,
        page_size: int | None = None,
    ) -> Self: ...
    def success(self, data: object, message: str = "") -> Self: ...
    def error(self, message: str) -> Self: ...
    def metadata(self, metadata: FlextTypes.Core.JsonDict) -> Self: ...
    def pagination(self, page: int, page_size: int, total: int) -> Self: ...
    def build(self) -> FlextApiResponse: ...

class PaginatedResponseBuilder:
    def __init__(self, config: PaginationConfig | None = None) -> None: ...
    def with_data(self, data: object) -> Self: ...
    def with_total(self, total: int) -> Self: ...
    def with_page(self, page: int) -> Self: ...
    def with_page_size(self, page_size: int) -> Self: ...
    def with_message(self, message: str) -> Self: ...
    def with_metadata(self, metadata: FlextTypes.Core.JsonDict) -> Self: ...
    def build(self) -> FlextApiResponse: ...

def create_client(config: FlextTypes.Core.JsonDict | None = None) -> FlextApiClient: ...
def build_query_from_params(
    params: FlextTypes.Core.JsonDict | None = None,
) -> FlextApiQuery: ...
def build_success_response(
    data: object, message: str = "", metadata: FlextTypes.Core.JsonDict | None = None
) -> FlextApiResponse: ...
def build_error_response(
    error: str, status_code: int = 400, metadata: FlextTypes.Core.JsonDict | None = None
) -> FlextApiResponse: ...
def build_paginated_response(config: PaginationConfig) -> FlextApiResponse: ...
def build_query(
    filters: list[FlextTypes.Core.JsonDict] | dict[str, object] | None = None,
    sorts: list[dict[str, str]] | None = None,
    page: int = 1,
    page_size: int = 20,
    search: str | None = None,
    fields: list[str] | None = None,
) -> FlextApiQuery: ...
