from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import StrEnum
from typing import TypeVar

from flext_core import FlextResult

__all__ = [
    "CacheEntry",
    "CacheInterface",
    "FileStorageBackend",
    "FlextApiStorage",
    "MemoryCache",
    "MemoryStorageBackend",
    "StorageBackend",
    "StorageBackendInterface",
    "StorageConfig",
    "TransactionContext",
    "create_file_storage",
    "create_memory_storage",
    "create_storage",
]

T = TypeVar("T")
K = TypeVar("K")
V = TypeVar("V")

class StorageBackend(StrEnum):
    MEMORY = "memory"
    FILE = "file"
    DATABASE = "database"
    REDIS = "redis"

@dataclass
class StorageConfig:
    backend: StorageBackend = ...
    connection_string: str | None = ...
    max_connections: int = ...
    timeout_seconds: float = ...
    enable_caching: bool = ...
    cache_ttl_seconds: int = ...
    enable_transactions: bool = ...
    serialization_format: str = ...
    file_path: str | None = ...
    namespace: str = ...

@dataclass
class CacheEntry[T]:
    value: T
    timestamp: float
    ttl_seconds: int
    def is_expired(self) -> bool: ...

@dataclass
class TransactionContext[V]:
    transaction_id: str = ...
    operations: list[tuple[str, str, V]] = ...
    started_at: float = ...
    is_active: bool = ...

class StorageBackendInterface[K, V](ABC):
    @abstractmethod
    async def get(self, key: K) -> FlextResult[V | None]: ...
    @abstractmethod
    async def set(
        self, key: K, value: V, ttl_seconds: int | None = None
    ) -> FlextResult[None]: ...
    @abstractmethod
    async def delete(self, key: K) -> FlextResult[bool]: ...
    @abstractmethod
    async def exists(self, key: K) -> FlextResult[bool]: ...
    @abstractmethod
    async def keys(self, pattern: str | None = None) -> FlextResult[list[K]]: ...
    @abstractmethod
    async def clear(self) -> FlextResult[None]: ...
    @abstractmethod
    async def close(self) -> FlextResult[None]: ...

class CacheInterface(ABC):
    @abstractmethod
    def get_cached(self, key: str) -> object | None: ...
    @abstractmethod
    def set_cached(self, key: str, value: object, ttl_seconds: int) -> None: ...
    @abstractmethod
    def delete_cached(self, key: str) -> bool: ...
    @abstractmethod
    def clear_cache(self) -> None: ...

class MemoryStorageBackend[V](StorageBackendInterface[str, V]):
    def __init__(self, config: StorageConfig) -> None: ...
    async def get(self, key: str) -> FlextResult[V | None]: ...
    async def set(
        self, key: str, value: V, ttl_seconds: int | None = None
    ) -> FlextResult[None]: ...
    async def delete(self, key: str) -> FlextResult[bool]: ...
    async def exists(self, key: str) -> FlextResult[bool]: ...
    async def keys(self, pattern: str | None = None) -> FlextResult[list[str]]: ...
    async def clear(self) -> FlextResult[None]: ...
    async def close(self) -> FlextResult[None]: ...

class FileStorageBackend[V](StorageBackendInterface[str, V]):
    def __init__(self, config: StorageConfig) -> None: ...
    async def get(self, key: str) -> FlextResult[V | None]: ...
    async def set(
        self, key: str, value: V, ttl_seconds: int | None = None
    ) -> FlextResult[None]: ...
    async def delete(self, key: str) -> FlextResult[bool]: ...
    async def exists(self, key: str) -> FlextResult[bool]: ...
    async def keys(self, pattern: str | None = None) -> FlextResult[list[str]]: ...
    async def clear(self) -> FlextResult[None]: ...
    async def close(self) -> FlextResult[None]: ...

class MemoryCache(CacheInterface):
    def __init__(self) -> None: ...
    def get_cached(self, key: str) -> object | None: ...
    def set_cached(self, key: str, value: object, ttl_seconds: int) -> None: ...
    def delete_cached(self, key: str) -> bool: ...
    def clear_cache(self) -> None: ...

class FlextApiStorage:
    def __init__(self, config: StorageConfig) -> None: ...
    async def get(
        self, key: str, *, use_cache: bool = True
    ) -> FlextResult[object | None]: ...
    async def set(
        self,
        key: str,
        value: object,
        ttl_seconds: int | None = None,
        transaction_id: str | None = None,
    ) -> FlextResult[None]: ...
    async def delete(
        self, key: str, transaction_id: str | None = None
    ) -> FlextResult[bool]: ...
    async def exists(self, key: str) -> FlextResult[bool]: ...
    async def keys(self, pattern: str | None = None) -> FlextResult[list[str]]: ...
    async def clear(self) -> FlextResult[None]: ...
    def begin_transaction(self) -> str: ...
    async def commit_transaction(self, transaction_id: str) -> FlextResult[None]: ...
    def rollback_transaction(self, transaction_id: str) -> FlextResult[None]: ...
    async def close(self) -> FlextResult[None]: ...

def create_storage(
    backend: str = "memory", **config_kwargs: object
) -> FlextApiStorage: ...
def create_memory_storage(
    namespace: str = "default",
    *,
    enable_caching: bool = True,
    cache_ttl_seconds: int = 300,
) -> FlextApiStorage: ...
def create_file_storage(
    file_path: str, namespace: str = "default", *, enable_caching: bool = True
) -> FlextApiStorage: ...
