__all__ = ["FlextAPIStorage"]

class FlextAPIStorage:
    def __init__(self) -> None: ...
    def get(self, key: str) -> object | None: ...
    def set(self, key: str, value: object) -> None: ...
    def delete(self, key: str) -> bool: ...
